In [59]:
import os 
from sklearn.naive_bayes import GaussianNB
from sklearn.feature_extraction.text import CountVectorizer
import glob
import numpy as np

fcf = glob.glob('/Users/Oliver/Desktop/香港大學研究生/Data Mining/Assignment2/dataset-news/*')
fcf = sorted(fcf)

message=[]
for i in range(len(fcf)):
    text = open(fcf[i],'r')
    raw_message = text.read()
    raw_message = raw_message.rstrip('\n')
    message=message + [raw_message]

count_vect = CountVectorizer(stop_words={'a','the','your','my','her','his','you','I','me','he','she','it','is','are','and','they','we','if','of'})
#count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(message)
X_train_counts.shape
X = X_train_counts.toarray()
print X

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 4 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [60]:
path = '/Users/Oliver/Desktop/香港大學研究生/Data Mining/Assignment2/dataset-news/' 
dir = os.listdir(path)              # dir is directory
file_name=[]
for d in dir:                        # d is file name 
    file_name=file_name+[d]
file_name = sorted(file_name)
file_seq = []
for d in file_name:
    if 'auto' in d:
        file_seq.append(0)
    elif 'baseball' in d:
        file_seq.append(1)
    elif 'electronics' in d:
        file_seq.append(2)
    elif 'hockey' in d:
        file_seq.append(3)
    elif 'ibm-hw' in d:
        file_seq.append(4)
    elif 'mac-hw' in d:
        file_seq.append(5)
    elif 'moto' in d:
        file_seq.append(6)
    elif 'pol-gun' in d:
        file_seq.append(7)
print file_seq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 

In [61]:
from sklearn.naive_bayes import GaussianNB
def gausNB(x_train,y_train,x_test,y_test):
    gnb = GaussianNB()
    gnb.fit(x_train, y_train)
    y_pred = gnb.predict(x_test)
    print "Number of mislabeled points out of a total %d points : %d" % \
    (x_test.shape[0],(y_test != y_pred).sum())
    accuracy=(y_test != y_pred).sum()
    return accuracy

from sklearn.naive_bayes import MultinomialNB
def MultiNB(x_train,y_train,x_test,y_test):
    mnb = MultinomialNB(alpha=1.0) 
    mnb.fit (x_train, y_train) 
    y_pred = mnb.predict(x_test)
    print "Number of mislabeled points out of a total %d points : %d" % \
    (x_test.shape[0],(y_test != y_pred).sum())
    accuracy=(y_test != y_pred).sum()
    return accuracy

In [62]:
import numpy as np
from sklearn.model_selection import KFold

X = X
y = file_seq
kf = KFold(n_splits=10,shuffle=True)
counter = 1
accuracy=0
for train, test in kf.split(X):
    print "%d Fold" % counter
    x_train, x_test = np.array(X)[train], np.array(X)[test]
    y_train, y_test = np.array(y)[train], np.array(y)[test]
    accuracy_gausNB = gausNB(x_train,y_train,x_test,y_test)+accuracy
    accuracy_MultiNB = MultiNB(x_train,y_train,x_test,y_test)+accuracy
    counter += 1
    # train and predict using your model
    # count the accuracy
accuracy_gausNB = float(accuracy_gausNB)
accuracy_gausNB = 1-(accuracy_gausNB/800)
accuracy_MultiNB = float(accuracy_MultiNB)
accuracy_MultiNB = 1-(accuracy_MultiNB/800)
print "accuracy of Gaussian naive bayes is %f" % (accuracy_gausNB)
print "accuracy of Multinomial naive bayes is %f" % (accuracy_MultiNB)
# print the average accuracy

1 Fold
Number of mislabeled points out of a total 80 points : 22
Number of mislabeled points out of a total 80 points : 26
2 Fold
Number of mislabeled points out of a total 80 points : 15
Number of mislabeled points out of a total 80 points : 17
3 Fold
Number of mislabeled points out of a total 80 points : 22
Number of mislabeled points out of a total 80 points : 21
4 Fold
Number of mislabeled points out of a total 80 points : 20
Number of mislabeled points out of a total 80 points : 17
5 Fold
Number of mislabeled points out of a total 80 points : 25
Number of mislabeled points out of a total 80 points : 26
6 Fold
Number of mislabeled points out of a total 80 points : 16
Number of mislabeled points out of a total 80 points : 10
7 Fold
Number of mislabeled points out of a total 80 points : 25
Number of mislabeled points out of a total 80 points : 19
8 Fold
Number of mislabeled points out of a total 80 points : 29
Number of mislabeled points out of a total 80 points : 18
9 Fold
Number of

In [63]:
new_label_test = np.random.randint(0, 8, 80)
print new_label_test


[3 7 7 0 1 5 3 2 4 3 4 6 1 4 6 6 5 0 7 2 5 7 5 5 5 5 0 6 3 1 1 5 7 6 6 7 2
 4 1 7 0 7 7 5 5 1 1 1 6 0 6 7 7 7 3 1 6 3 3 0 0 5 3 2 3 5 5 2 0 6 0 6 0 2
 7 3 5 5 3 2]


In [64]:
import numpy as np
from sklearn.model_selection import KFold

X = X
y = file_seq
kf = KFold(n_splits=10,shuffle=True)
counter = 1
accuracy=0
for train, test in kf.split(X):
    print "%d Fold" % counter
    x_train, x_test = np.array(X)[train], np.array(X)[test]
    #y_train, y_test = np.array(y)[train], np.array(y)[test]
    y_test=new_label_test
    accuracy_gausNB = gausNB(x_train,y_train,x_test,y_test)+accuracy
    accuracy_MultiNB = MultiNB(x_train,y_train,x_test,y_test)+accuracy
    counter += 1
    # train and predict using your model
    # count the accuracy
accuracy_gausNB = float(accuracy_gausNB)
accuracy_gausNB = (accuracy_gausNB/800)
accuracy_MultiNB = float(accuracy_MultiNB)
accuracy_MultiNB = (accuracy_MultiNB/800)
print "accuracy of Gaussian naive bayes is %f" % (accuracy_gausNB)
print "accuracy of Multinomial naive bayes is %f" % (accuracy_MultiNB)
# print the average accuracy

1 Fold
Number of mislabeled points out of a total 80 points : 70
Number of mislabeled points out of a total 80 points : 70
2 Fold
Number of mislabeled points out of a total 80 points : 76
Number of mislabeled points out of a total 80 points : 74
3 Fold
Number of mislabeled points out of a total 80 points : 73
Number of mislabeled points out of a total 80 points : 74
4 Fold
Number of mislabeled points out of a total 80 points : 74
Number of mislabeled points out of a total 80 points : 75
5 Fold
Number of mislabeled points out of a total 80 points : 71
Number of mislabeled points out of a total 80 points : 74
6 Fold
Number of mislabeled points out of a total 80 points : 73
Number of mislabeled points out of a total 80 points : 75
7 Fold
Number of mislabeled points out of a total 80 points : 72
Number of mislabeled points out of a total 80 points : 74
8 Fold
Number of mislabeled points out of a total 80 points : 72
Number of mislabeled points out of a total 80 points : 70
9 Fold
Number of

In [65]:


path = '/Users/Oliver/Desktop/香港大學研究生/Data Mining/Assignment2/dataset-news/' # 替换为你的路径
dir = os.listdir(path)                  # dir是目录下的全部文件
file_name=[]
for d in dir:                        # d是每一个文件的文件名
    file_name=file_name+[d]
file_name = sorted(file_name)
#print file_name
file_seq = []
file_label = []
file_label2 = []
for d in file_name:
    if 'hockey' in d:
        file_seq.append(0)
        file_label.append(0)
    elif 'mac-hw' in d:
        file_seq.append(0)
        file_label.append(1)
    elif 'pol-gun' in d:
        file_seq.append(0)
        file_label.append(2)
    
        
    elif 'electronics' in d:
        file_seq.append(2)
        file_label2.append(6)
    elif 'ibm-hw' in d:
        file_seq.append(2)
        file_label2.append(7)
    elif 'mac-hw' in d:
        file_seq.append(2)
        file_label2.append(8)
    else:
        file_seq.append(1)

#print file_seq

#find = 0
find = 2
file_seq_0 = [i for i,v in enumerate(file_seq) if v==find]
#print file_seq_0
X_train_test1=[]
#print X_test1
for X_test1 in file_seq_0:
    X_app=X[X_test1].tolist()
    X_train_test1.append(X_app)

X_train_test1=np.array(X_train_test1)

import numpy as np
from sklearn.model_selection import KFold

X = X_train_test1
y = file_label
kf = KFold(n_splits=10,shuffle=True)
counter = 1
accuracy=0
for train, test in kf.split(X):
    print "%d Fold" % counter
    x_train, x_test = np.array(X)[train], np.array(X)[test]
    y_train, y_test = np.array(y)[train], np.array(y)[test]
    accuracy_gausNB = gausNB(x_train,y_train,x_test,y_test)+accuracy
    accuracy_MultiNB = MultiNB(x_train,y_train,x_test,y_test)+accuracy
    counter += 1
    # train and predict using your model
    # count the accuracy
accuracy_gausNB = float(accuracy_gausNB)
accuracy_gausNB = 1-(accuracy_gausNB/800)
accuracy_MultiNB = float(accuracy_MultiNB)
accuracy_MultiNB = 1-(accuracy_MultiNB/800)
print "accuracy of Gaussian naive bayes is %f" % (accuracy_gausNB)
print "accuracy of Multinomial naive bayes is %f" % (accuracy_MultiNB)
# print the average accuracy



1 Fold
Number of mislabeled points out of a total 20 points : 3
Number of mislabeled points out of a total 20 points : 3
2 Fold
Number of mislabeled points out of a total 20 points : 6
Number of mislabeled points out of a total 20 points : 5
3 Fold
Number of mislabeled points out of a total 20 points : 7
Number of mislabeled points out of a total 20 points : 3
4 Fold
Number of mislabeled points out of a total 20 points : 4
Number of mislabeled points out of a total 20 points : 3
5 Fold
Number of mislabeled points out of a total 20 points : 4
Number of mislabeled points out of a total 20 points : 7
6 Fold
Number of mislabeled points out of a total 20 points : 0
Number of mislabeled points out of a total 20 points : 0
7 Fold
Number of mislabeled points out of a total 20 points : 5
Number of mislabeled points out of a total 20 points : 3
8 Fold
Number of mislabeled points out of a total 20 points : 5
Number of mislabeled points out of a total 20 points : 5
9 Fold
Number of mislabeled poin